### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by voroskoi** [psilva261/timsort#12]
Hi,

First of all, thank You very much for this work! While I was porting timsort to zig, I have noticed, that `v2/timsortint.go` is missing a `return` statement after line 110. I am not that familiar with the codebase, but it could be missing elsewhere too.
Not a big deal, as only affects inputs below `minMerge`, but should be fixed anyway.

Thanks,

**Comment by psilva261** [comment]
Hi, Thanks for the find! Yeah true, same in timsort.go. That's definitely some unnecessary cpu cycles. Will push a fix soon'ish
