### ISSUE TITLE
Broken algorithm?

### ISSUE THREAD

**Issue by dsamarin** [psilva261/timsort#6]
After a quick review of the code, I've noticed a few suspects.

### 1) Binary search integer overflow

https://github.com/psilva261/timsort/blob/4537dc9bd679bfb730b72f2e8c33b46676521337/timsort.go#L277

This fails for large values of `low` and `high`. If the sum overflows to a negative value, this will fail with an out of bounds error. There are two ways to fix this.

```go
mid := left + (right - left) / 2
```

```go
mid := int(uint(left + right) >> 1) // Used in Go package sort.Search
```

See: [Extra, Extra - Read All About It: Nearly All Binary Searches and Mergesorts are Broken](https://ai.googleblog.com/2006/06/extra-extra-read-all-about-it-nearly.html)

### 2) Timsort invariant violation

I noticed that the implementation of `mergeCollapse` is similar to the one in an old version of CPython. 

https://github.com/psilva261/timsort/blob/4537dc9bd679bfb730b72f2e8c33b46676521337/timsort.go#L434-L440

See: [Proving that Android’s, Java’s and Python’s sorting algorithm is broken (and showing how to fix it)](http://www.envisage-project.eu/proving-android-java-and-python-sorting-algorithm-is-broken-and-how-to-fix-it/)

**Comment by psilva261** [comment]
Hey, thanks for the comments. Feel free to make a pull request - otherwise I will fix the first issue soonish. To be honest, I'm not sure whether the whole thing compiles at the moment with the current Go version

**Comment by dsamarin** [comment]
Great, will do. I've made the changes locally and took some benchmarks with Go 1.10.3 in a VM to satisfy my curiosity.

```
BenchmarkTimsortInterXor1M-4                  10         184175628 ns/op        16776019 B/op         16 allocs/op
BenchmarkStandardSortXor1M-4                  20          81385816 ns/op               0 B/op          0 allocs/op
BenchmarkTimsortInterSorted1M-4              100          12538559 ns/op         8391345 B/op          5 allocs/op
BenchmarkStandardSortSorted1M-4               20          95994855 ns/op               0 B/op          0 allocs/op
BenchmarkTimsortInterRevSorted1M-4           100          15162427 ns/op         8391345 B/op          5 allocs/op
BenchmarkStandardSortRevSorted1M-4            10         100411558 ns/op               0 B/op          0 allocs/op
BenchmarkTimsortInterRandom1M-4                2         661192462 ns/op        16710352 B/op         15 allocs/op
BenchmarkStandardSortRandom1M-4                5         246840102 ns/op               0 B/op          0 allocs/op
```

So this benchmark shows 8x performance for sorted data, 6x for reverse sorted data, 0.5x for xor and .37x for random data.

**Comment by psilva261** [comment]
Oh nice, this is pretty nice. Looks like it got better again over time. I noticed at earlier Go version the Garbage collector was pretty stressed but there have been major changes to it. (Or it's your computer ;)) I guess I'll make some more extensive benchmarks and update the Benchmarks.md
